#include "imu_driver.h"
#include <stddef.h>

/* --- Hardware Specific Includes --- */
#if !IMU_SIMULATION_MODE
    // Note: Change this header if you use an STM32 series other than F4
    #include "stm32f4xx_hal.h" 
    
    // The I2C handle generated by STM32CubeMX in main.c
    extern I2C_HandleTypeDef hi2c1; 
    
    // MPU6050 Default I2C Address (shifted left by 1 for STM32 HAL)
    #define MPU6050_ADDR (0x68 << 1) 
#endif

/* --- Internal State --- */
/** * @brief Internal simulation counter. 
 * 'static' ensures it cannot be accessed outside of this specific file.
 */
static int16_t sim_counter = 0;

IMU_Status_t IMU_Init(void) {
#if IMU_SIMULATION_MODE
	// Reset the simulation state
	sim_counter = 0;
	return IMU_OK;

#else
	uint8_t check;
	uint8_t data;
	
	// Check if device is alive (WHO_AM_I register is 0x75)
	// It should return 0x68 if it's an MPU6050
	if (HAL_I2C_Mem_Read(&hi2c1, MPU6050_ADDR, 0x75, 1, &check, 1, 100) != HAL_OK) {
		return IMU_ERR_NOT_FOUND;
	}

	if (check != 0x68) {
		return IMU_ERR_NOT_FOUND;		// Found something, but not an MPU6050
	}
	
	// Wake up MPU6050 (Write 0 to Power Management 1 register: 0x6B)
	data = 0x00;
	if (HAL_I2C_Mem_Write(&hi2c1, MPU6050_ADDR, 0x6B, 1, &data, 1, 100) != HAL_OK) {
		return IMU_ERR_I2C_FAIL;
	}
	
	// Here we'll configure Gyro & Accel ranges later on
	
	return IMU_OK
#endif
}

IMU_Status_t IMU_Get_Reading(IMU_Reading_t* out_reading) {
	
	// Safety check
	if (out_reading == NULL) {
		return IMU_ERR_INVALID_ARG;
	}
	
#if IMU_SIMULATION_MODE
	// Generate predictable "Sawtooth" data for PC integration testing
	out_reading->accel_x = sim_counter;
	out_reading->accel_y = sim_counter + 100;
	out_reading->accel_z = sim_counter + 200;
	
	out_reading->gyro_x = sim_counter / 2;
	out_reading->gyro_y = (sim_counter / 2) + 50;
	out_reading->gyro_z = (sim_counter / 2) + 100;
	
	// Increment counter (will naturally wrap around at int16_t max)
	sim_counter += 10;
	
	return IMU_OK;

#else
	// The MPU6050 provides 14 bytes: 6 for accel, 2 for temp, 6 for Gyro
	uint8_t raw_data[14];
	
	// Burst read starting from ACCELXOUT_H (0x3B)
	if (HAL_I2C_Mem_Read(&hi2c1, MPU6050_ADDR, 0x3B, 1, raw_data, 14, 100) != HAL_OK) {
		return IMU_ERR_I2C_FAIL;
	}
	
	// Pack bytes into 16-bit integers (Converting from Big-Endian to Little-Endian)
	out_reading->accel_x = (int16_t)((raw_data[0] << 8) | raw_data[1]);
	out_reading->accel_y = (int16_t)((raw_data[2] << 8) | raw_data[3]);
	out_reading->accel_z = (int16_t)((raw_data[4] << 8) | raw_data[5]);
	
	// We skip raw_data[6] and raw_data[7] for now, temperature values
	
	out_reading->gyro_x = (int16_t)((raw_data[8] << 8) | raw_data[9]);
	out_reading->gyro_y = (int16_t)((raw_data[10] << 8) | raw_data[11]);
	out_reading->gyro_z = (int16_t)((raw_data[12] << 8) | raw_data[13]);
	
	return IMU_OK;
#endif
}